CREATE TABLE infoentity (
ID BIGINT NOT NULL AUTO_INCREMENT, 
DTYPE VARCHAR(31), 
EMAIL VARCHAR(255), 
ADDRESS_ID BIGINT, 
CVR INT, 
DESCRIPTION VARCHAR(255), 
MARKETVALUE VARCHAR(255), 
`NAME` VARCHAR(255), 
NUMOFEMPLOYEES INT, 
FIRSTNAME VARCHAR(255), 
LASTNAME VARCHAR(255), 
PRIMARY KEY (ID));

CREATE TABLE address (
ID BIGINT NOT NULL AUTO_INCREMENT, 
ADDITIONALINFO VARCHAR(255), 
STREETNAME VARCHAR(255), 
CITYINFO_ID BIGINT, 
PRIMARY KEY (ID));

CREATE TABLE cityinfo (
ID BIGINT NOT NULL AUTO_INCREMENT, 
CITY VARCHAR(255), 
ZIPCODE INT, 
PRIMARY KEY (ID));

CREATE TABLE hobby (
ID BIGINT NOT NULL AUTO_INCREMENT, 
DESCRIPTION VARCHAR(255), 
`NAME` VARCHAR(255), 
PRIMARY KEY (ID));

CREATE TABLE infoentity_hobby (
hobbies_ID BIGINT NOT NULL, 
persons_ID BIGINT NOT NULL, 
PRIMARY KEY (hobbies_ID, persons_ID));

CREATE TABLE phone (
ID BIGINT NOT NULL AUTO_INCREMENT, 
DESCRIPTION VARCHAR(255), 
PHONENUMBER INT, 
INFOENTITY_ID BIGINT, 
PRIMARY KEY (ID));
