INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Company', 'adasdasd@sdsfsdfsf.shit', NULL, NULL, NULL, NULL, NULL, NULL, 'freddy', NULL);
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', 'rihards.pacevics@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, 'Rihards', 'Pacevics');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', 'rihards.pacevics@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, 'Rihards', 'Pacevics');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Company', 'rihards.pacevics@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, 'Rihards', 'Pacevics');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Company', 'adasdasd@sdsfsdfsf.shit', NULL, NULL, NULL, NULL, NULL, NULL, 'freddy', NULL);
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Company', 'adasdasd@sdsfsdfsf.shit', NULL, NULL, NULL, NULL, NULL, NULL, 'freddy', NULL);
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', 'adasdasd@sdsfsdfsf.shit', NULL, NULL, NULL, NULL, NULL, NULL, 'freddy', NULL);
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', 'rihards.pacevics@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, 'Rihards', 'Pacevics');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', 'rihards.pacevics@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, 'Rihards', 'Pacevics');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', 'lol@lol.com', NULL, NULL, NULL, NULL, NULL, NULL, 'frederiko', 'bulshito');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', 'rihards.pacevics@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, 'Rihards', 'Pacevics');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', 'rihards.pacevics@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, 'Rihards', 'Pacevics');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', 'lol@lol.com', NULL, NULL, NULL, NULL, NULL, NULL, 'William', 'Bech');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Company', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Company', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', '', NULL, NULL, NULL, NULL, NULL, NULL, '', '');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', 'rihards.pacevics@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, 'Rihards', 'Pacevics');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Person', 'rihards.pacevics@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, 'Rihards', 'Pacevics');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Company', 'rihards.pacevics@gmail.com', NULL, NULL, NULL, NULL, NULL, NULL, 'Rihards', 'Pacevics');
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Company', 'adasdasd@sdsfsdfsf.shit', NULL, NULL, NULL, NULL, NULL, NULL, 'freddy', NULL);
INSERT INTO infoentity (`DTYPE`, `EMAIL`, `ADDRESS_ID`, `CVR`, `DESCRIPTION`, `MARKETVALUE`, `NAME`, `NUMOFEMPLOYEES`, `FIRSTNAME`, `LASTNAME`) 
	VALUES ('Company', 'adasdasd@sdsfsdfsf.shit', NULL, NULL, NULL, NULL, NULL, NULL, 'freddy', 'pigure');